### ISSUE TITLE
Docker Transmission

### ISSUE THREAD

**Issue by XavierLee-0** [WhymustIhaveaname/Transmission-Block-Xunlei#2]
请问这个脚本怎么用在docker版的transmission上？

**Comment by WhymustIhaveaname** [comment]
感谢使用！估计要进入 docker 的 terminal 手动安装保存。

我上次用 docker 还是很久之前了，具体的命令记不清了但是感觉和这个链接说的差不多 https://docs.docker.com/engine/reference/commandline/exec/

**Comment by XavierLee-0** [comment]
已解决 谢谢 脚本很好用
