### ISSUE TITLE
搭建笔记中配置步骤中有一处transmission写成了transmsision

### ISSUE THREAD

**Issue by mccrena** [WhymustIhaveaname/Transmission-Block-Xunlei#5]
在此处
https://github.com/WhymustIhaveaname/Transmission-Block-Xunlei/blob/main/%E6%90%AD%E5%BB%BA%E7%AC%94%E8%AE%B0.md#:~:text=vim%20/var/lib/transmsision%2Ddaemon/info/settings.json

**Comment by mccrena** [comment]
关于这行代码
https://github.com/WhymustIhaveaname/Transmission-Block-Xunlei/blob/main/%E6%90%AD%E5%BB%BA%E7%AC%94%E8%AE%B0.md#:~:text=%E6%88%91%E4%BF%AE%E6%94%B9%E4%BA%86-,/var/lib/transmsision%2Ddaemon/info,-%E4%B8%AD%E7%9A%84%3A
的也错了

**Comment by WhymustIhaveaname** [comment]
已更正，谢谢！
